FROM mongo:7.0.12

RUN mkdir -p /mongo/data /backup

COPY mongod.conf /etc/mongod.conf
COPY star-ecommerce /backup
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

CMD ["/docker-entrypoint.sh"]
